import React from 'react';
import {Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {ScreenBackground} from '@components/backgrounds/ScreenBackground';
import {ThemedText} from '@components/common/ThemedText';
import {useTheme} from '@hooks/useTheme';
import {THEME_META} from '@themes/registry';
import {ANIMATION_GROUPS, ANIMATION_META} from '@animation/config/animationKeys';
import {useThemeStore} from '@store/useThemeStore';
import {useAnimationStore} from '@store/useAnimationStore';
import type {AnimationKey} from '@domain/animation';

export function SettingsScreen(): React.JSX.Element {
  const {theme} = useTheme(); const activeTheme = useThemeStore(s => s.themeId); const setTheme = useThemeStore(s => s.setTheme); const flags = useAnimationStore(s => s.flags); const fpsTarget = useAnimationStore(s => s.fpsTarget); const setFlag = useAnimationStore(s => s.setFlag); const setFpsTarget = useAnimationStore(s => s.setFpsTarget);
  return <ScreenBackground><ScrollView contentContainerStyle={styles.content}><Text style={[styles.eyebrow, {color: theme.colors.accent}]}>CONTROL ROOM</Text><ThemedText variant="title">Settings</ThemedText><Section title="Visual language"><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.themes}>{THEME_META.map(item => <Pressable key={item.id} onPress={() => setTheme(item.id)} accessibilityRole="radio" accessibilityState={{checked: activeTheme === item.id}} style={[styles.themeCard, {backgroundColor: theme.colors.surface, borderColor: activeTheme === item.id ? theme.colors.accent : theme.colors.border}]}><View style={styles.swatches}>{item.swatch.map(color => <View key={color} style={[styles.swatch, {backgroundColor: color}]} />)}</View><Text style={[styles.themeName, {color: theme.colors.text}]}>{item.name}</Text><Text numberOfLines={2} style={[styles.themeDescription, {color: theme.colors.textMuted}]}>{item.description}</Text></Pressable>)}</ScrollView></Section><Section title="Frame target"><View style={[styles.segment, {backgroundColor: theme.colors.surface, borderColor: theme.colors.border}]}>{([60, 120] as const).map(value => <Pressable key={value} onPress={() => setFpsTarget(value)} style={[styles.segmentItem, fpsTarget === value && {backgroundColor: theme.colors.accent}]}><Text style={[styles.segmentText, {color: fpsTarget === value ? theme.colors.background : theme.colors.text}]}>{value} FPS</Text></Pressable>)}</View><Text style={[styles.helper, {color: theme.colors.textMuted}]}>Higher refresh targets use more battery and depend on the device display.</Text></Section><Section title="Motion controls"><Text style={[styles.helper, {color: theme.colors.textMuted}]}>Each effect is independent. Turning one off never disables the others.</Text>{ANIMATION_GROUPS.map(group => <View key={group} style={styles.group}><Text style={[styles.groupTitle, {color: theme.colors.accent}]}>{group.toUpperCase()}</Text>{ANIMATION_META.filter(item => item.group === group).map(item => <Pressable key={item.key} onPress={() => setFlag(item.key as AnimationKey, !flags[item.key])} style={[styles.row, {borderBottomColor: theme.colors.border}]}><View style={styles.rowInfo}><Text style={[styles.rowTitle, {color: theme.colors.text}]}>{item.label}</Text><Text style={[styles.rowDescription, {color: theme.colors.textMuted}]}>{item.description}</Text></View><View style={[styles.toggle, {backgroundColor: flags[item.key] ? theme.colors.accent : theme.colors.surfaceAlt}]}><View style={[styles.knob, {backgroundColor: flags[item.key] ? theme.colors.background : theme.colors.textMuted, alignSelf: flags[item.key] ? 'flex-end' : 'flex-start'}]} /></View></Pressable>)}</View>)}</Section></ScrollView></ScreenBackground>;
}
function Section({title, children}: {title: string; children: React.ReactNode}): React.JSX.Element {const {theme} = useTheme(); return <View style={styles.section}><Text style={[styles.sectionTitle, {color: theme.colors.text}]}>{title}</Text>{children}</View>}
const styles = StyleSheet.create({content: {padding: 20, paddingBottom: 40}, eyebrow: {fontSize: 10, fontWeight: '800', letterSpacing: 1.5, marginBottom: 8}, section: {marginTop: 30}, sectionTitle: {fontSize: 16, fontWeight: '800', marginBottom: 14}, themes: {gap: 10, paddingRight: 20}, themeCard: {width: 150, minHeight: 128, padding: 12, borderRadius: 15, borderWidth: 1}, swatches: {flexDirection: 'row', gap: 4, marginBottom: 14}, swatch: {height: 20, flex: 1, borderRadius: 5}, themeName: {fontSize: 13, fontWeight: '800'}, themeDescription: {fontSize: 10, lineHeight: 14, marginTop: 4}, segment: {flexDirection: 'row', borderWidth: 1, borderRadius: 12, padding: 4, gap: 4}, segmentItem: {flex: 1, alignItems: 'center', paddingVertical: 12, borderRadius: 8}, segmentText: {fontSize: 13, fontWeight: '800'}, helper: {fontSize: 12, lineHeight: 18, marginTop: 10}, group: {marginTop: 18}, groupTitle: {fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginBottom: 4}, row: {minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 14, borderBottomWidth: StyleSheet.hairlineWidth}, rowInfo: {flex: 1, gap: 3}, rowTitle: {fontSize: 14, fontWeight: '700'}, rowDescription: {fontSize: 11, lineHeight: 16}, toggle: {width: 43, height: 25, borderRadius: 14, justifyContent: 'center', paddingHorizontal: 3}, knob: {width: 19, height: 19, borderRadius: 10}});
