import React, {useEffect} from 'react';
import {Image, Pressable, StyleSheet, Text, View} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import {ScreenBackground} from '@components/backgrounds/ScreenBackground';
import {ThemedText} from '@components/common/ThemedText';
import {PressableScale} from '@components/common/PressableScale';
import {useTheme} from '@hooks/useTheme';
import {useNowPlaying} from '@hooks/useNowPlaying';
import {usePlayerStore} from '@store/usePlayerStore';
import {useQueueStore} from '@store/useQueueStore';
import {play, pause, skipToNext, skipToPrevious} from '@services/audio/playbackController';

export function PlayerScreen(): React.JSX.Element {
  useNowPlaying(); const navigation = useNavigation<any>(); const {theme} = useTheme(); const track = usePlayerStore(s => s.currentTrack); const status = usePlayerStore(s => s.status); const position = usePlayerStore(s => s.position); const duration = usePlayerStore(s => s.duration); const queue = useQueueStore(s => s.queue);
  useEffect(() => {if (queue.length > 0 && !track) void play();}, [queue.length, track]);
  const progress = duration > 0 ? Math.min(position / duration, 1) : 0; const playing = status === 'playing';
  return <ScreenBackground><View style={styles.container}><View style={styles.top}><Pressable onPress={() => navigation.goBack()}><Text style={[styles.back, {color: theme.colors.text}]}>‹</Text></Pressable><Text style={[styles.now, {color: theme.colors.textMuted}]}>NOW PLAYING</Text><View style={{width: 28}} /></View>{track ? <><View style={[styles.artWrap, {backgroundColor: theme.colors.surfaceAlt, borderColor: theme.colors.border}]}>{track.artwork ? <Image source={{uri: track.artwork}} style={styles.art} /> : <Text style={[styles.note, {color: theme.colors.accent}]}>♪</Text>}</View><View style={styles.info}><ThemedText variant="title">{track.title}</ThemedText><Text style={[styles.artist, {color: theme.colors.accent}]}>{track.artist}</Text><Text style={[styles.album, {color: theme.colors.textMuted}]}>{track.album}</Text></View><View style={styles.scrub}><View style={[styles.track, {backgroundColor: theme.colors.surfaceAlt}]}><View style={[styles.fill, {backgroundColor: theme.colors.accent, width: `${progress * 100}%`}]} /></View><View style={styles.times}><Text style={[styles.time, {color: theme.colors.textMuted}]}>{formatTime(position)}</Text><Text style={[styles.time, {color: theme.colors.textMuted}]}>{formatTime(duration)}</Text></View></View><View style={styles.controls}><PressableScale onPress={() => void skipToPrevious()}><Text style={[styles.secondary, {color: theme.colors.text}]}>|‹</Text></PressableScale><PressableScale onPress={() => void (playing ? pause() : play())} style={[styles.main, {backgroundColor: theme.colors.accent}]}><Text style={[styles.mainGlyph, {color: theme.colors.background}]}>{playing ? 'Ⅱ' : '▶'}</Text></PressableScale><PressableScale onPress={() => void skipToNext()}><Text style={[styles.secondary, {color: theme.colors.text}]}>›|</Text></PressableScale></View></> : <View style={styles.empty}><Text style={[styles.emptyTitle, {color: theme.colors.text}]}>Choose a track</Text><Text style={[styles.album, {color: theme.colors.textMuted}]}>Your player is ready for local audio.</Text></View>}</View></ScreenBackground>;
}
function formatTime(seconds: number): string {if (!Number.isFinite(seconds)) return '0:00'; return `${Math.floor(seconds / 60)}:${Math.floor(seconds % 60).toString().padStart(2, '0')}`;}
const styles = StyleSheet.create({container: {flex: 1, paddingHorizontal: 24, paddingTop: 18}, top: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'}, back: {fontSize: 38, lineHeight: 34}, now: {fontSize: 10, fontWeight: '800', letterSpacing: 2}, artWrap: {marginTop: 48, alignSelf: 'center', width: 292, height: 292, borderRadius: 28, padding: 9, borderWidth: 1}, art: {width: '100%', height: '100%', borderRadius: 21}, note: {fontSize: 94, flex: 1, textAlign: 'center', textAlignVertical: 'center'}, info: {alignItems: 'center', marginTop: 30, gap: 7}, artist: {fontSize: 16, fontWeight: '800'}, album: {fontSize: 13}, scrub: {marginTop: 34}, track: {height: 5, borderRadius: 4, overflow: 'hidden'}, fill: {height: '100%', borderRadius: 4}, times: {flexDirection: 'row', justifyContent: 'space-between', marginTop: 9}, time: {fontSize: 11, fontVariant: ['tabular-nums']}, controls: {flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 42, marginTop: 26}, secondary: {fontSize: 22, fontWeight: '800'}, main: {width: 64, height: 64, borderRadius: 32, alignItems: 'center', justifyContent: 'center'}, mainGlyph: {fontSize: 21, fontWeight: '900'}, empty: {flex: 1, justifyContent: 'center', alignItems: 'center', gap: 10}, emptyTitle: {fontSize: 22, fontWeight: '800'}});
